---
title: "Final Project: The Streams Analysis of Pop Music in 2018"
author: "Chong Wang, Tianping Wu, Zhenning Zhao, Zhiyang Lin"
date: "2019/5/16"
output:
  md_document:
    variant: markdown_github
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(foreach)
library(tidyverse)
library(gbm)
library(randomForest)
```

# The Streams Analysis of Pop Music in 2018

By Chong Wang, Tianping Wu, Zhenning Zhao, Zhiyang Lin

## Introduction

Popular music market is extremely large, especially in recent years. Pop songs inspire generations from all walks of life. Every day, oceans of pop tracks jump on to the Top 200 List of Spotify. In this project, we analysed the data of the 2018 popular music database from Spotify.com, in order to help the big digital music server improve playlist song recommendations and to help the record companies make decisions on which album to promote according to the predictions on the playing streams.

This project mainly answers the following questions: first, predict the streams of the tracks; and second, analysis the pattern of the popularity trend. To answer the first question, we used stepwise method, the lasso method and the random forest and boosting to build a prediction model of the streams of the tracks, with the features of the songs and the albums as predictor. In order to answer the second question, we first used PCA and K-means to cluster the songs by features, dividing songs into different categories. Then we plotted the trend of the popularity of different type of songs, showing the change in the trend of the listener’s taste.

## Data

```{data_intro, include=FALSE}
myurl <- "https://raw.githubusercontent.com/znzhao/ECO395M-HW-zz5339/master/Final%20Project/data/sounddata_2018.csv"
sounddata_2018 <- read.csv(url(myurl), row.names=1)
sounddata_2018 = subset(sounddata_2018,is.na(sounddata_2018$valence)==FALSE)
sounddata_2018$key = sounddata_2018$key %>% as.factor()
temp = model.matrix( ~ key-1,sounddata_2018)
sounddata_2018 = cbind(sounddata_2018,temp)
sounddata_2018$time_signature = sounddata_2018$time_signature %>% as.factor()
temp = model.matrix( ~ time_signature-1,sounddata_2018)
sounddata_2018 = cbind(sounddata_2018,temp)
temp = model.matrix( ~ explicit-1,sounddata_2018)
sounddata_2018 = cbind(sounddata_2018,temp)
relseaseDuration = as.Date(sounddata_2018$releaseDate)
temp = c()
for (i in c(1:length(relseaseDuration))) {
  temp = c(temp,as.Date("2019/1/1", origin = "1990/1/1"))
}
relseaseDuration = as.numeric(as.Date(temp, origin = "1990/1/1")-relseaseDuration)
sounddata_2018 = cbind(sounddata_2018, relseaseDuration)
#delete uncategorized label "unused attributes"
Clean_data <- subset(sounddata_2018, select = -c(releaseDate, artist_name, album_name, explicit, is_local, name, popularity, key0, key, time_signature, time_signature1, explicitFALSE))
Clean_data$acousticness <- Clean_data$acousticness %>% as.numeric()

myurl <- "https://raw.githubusercontent.com/znzhao/ECO395M-HW-zz5339/master/Final%20Project/data/sounddata_2018weekly.csv"
sounddata_2018_weekly <- read.csv(url(myurl))
```

The dataset that we use comes from spotify.com. Spotify is one of the biggest digital music servicer that gives you access to many songs. From https://spotifycharts.com, we have the weekly data of the top 200 songs in the US. We use the data of 2018, giving us 1,497 different songs.

Fortunately, Spotify has a public API, which provides us many useful features of the songs. We use python robot to gather the data of not only the song features but also the data of the artists and the album. In the end, the formal dataset includes the following variables:

Table1: Variable Descriptions

|  variables   |   descriptions    |
|----------------|----------------------|
|id|song ID|
|duration_ms_x|   The duration of the track in milliseconds. |
|acousticness|A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic.|
|danceability|Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.|
|energy|Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.|
|instrumentalness|Predicts whether a track contains no vocals. “Ooh” and “aah” sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly “vocal”. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.|
| liveness|Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.|
|loudness|The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typical range between -60 and 0 db.|
|mode|Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.|
|speechiness|Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.|
| tempo|The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.|
|valence|A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).|
|key|The estimated overall key of the track. Integers map to pitches using standard Pitch Class notation . E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1.|
|time_signature|An estimated overall time signature of a track. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure).|
|relseaseDuration|The date the album was first released.|

The explanation of the variables comes from the following link: https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/ Although this project only run on the dataset of 2018, we can do similar analysis for spotify for more songs and more recent data with similar method.



```{predicition, include=FALSE}
#Streams as an dependent variable
#stepwise
null1 = lm(Streams~1, data=Clean_data)
medium1 = lm(Streams ~ ., data=Clean_data)
big1 = lm(Streams ~ (.)^2, data=Clean_data)
stepwise1 = step(null1, scope=formula(medium1), dir="both", trace = FALSE)
stepwise2 = step(medium1, scope=formula(big1), dir="both", trace = FALSE)
model1 = formula(stepwise1)
model2 = formula(stepwise2)
length(coef(stepwise1))
AICc(stepwise1)
length(coef(stepwise2))
AICc(stepwise2)
qplot(x = relseaseDuration, y = Streams, data = Clean_data)

#Lasso
Stx1 = sparse.model.matrix(Streams ~ ., data=Clean_data)[,-1] 
Sty1 = Clean_data$Streams
Stlasso1 = gamlr(Stx1, Sty1, lambda.min.ratio=0.000001)
plot(log(Stlasso1$lambda), AICc(Stlasso1))
plot(Stlasso1)
Stbeta1 = coef(Stlasso1)

p1 <- dimnames(Stbeta1)[[1]]
p2 <- c()
for (i in c(1:length(Stbeta1))){
  p2 <- c(p2, as.list(Stbeta1)[[i]])
}
model3 = c("Streams ~ ")
for (i in c(2:length(Stbeta1))){
  if (p2[i] != 0){
    if (model3 == "Streams ~ "){
      model3 = paste(model3, p1[i])
    }
    else{
      model3 = paste(model3,"+", p1[i])
    }
  }
}
model3 <- as.formula(model3)
model3

Stx2 = sparse.model.matrix(Streams ~ (.)^2, data=Clean_data)[,-1] 
Sty2 = Clean_data$Streams
Stlasso2 = gamlr(Stx2, Sty2, lambda.min.ratio=0.00000001)
plot(log(Stlasso2$lambda), AICc(Stlasso2))
plot(Stlasso2)
Stbeta2 = coef(Stlasso2)

p1 <- dimnames(Stbeta2)[[1]]
p2 <- c()
for (i in c(1:length(Stbeta2))){
  p2 <- c(p2, as.list(Stbeta2)[[i]])
}
model4 = c("Streams ~ ")
for (i in c(2:length(Stbeta2))){
  if (p2[i] != 0){
    if (model4 == "Streams ~ "){
      model4 = paste(model4, p1[i])
    }
    else{
      model4 = paste(model4,"+", p1[i])
    }
  }
}
model4 <- as.formula(model4)
model4
#optimal lambda
log(Stlasso1$lambda[which.min(AICc(Stlasso1))])
sum(Stbeta1!=0)
log(Stlasso2$lambda[which.min(AICc(Stlasso2))])
sum(Stbeta2!=0)

#trees and random forests
# split into a training and testing set
N = nrow(Clean_data)
train_frac = 0.8
N_train = floor(train_frac*N)
N_test = N - N_train
train_ind = sample.int(N, N_train, replace=FALSE) %>% sort
Clean_data_train = Clean_data[train_ind,]
Clean_data_test = Clean_data[-train_ind,]

# 1. bagging:
rmse_forest = c()
for (K in c(1:27)){
  forest1 = randomForest(Streams ~ ., mtry=K, nTree=100, data=Clean_data_train)
  yhat_forest_test = predict(forest1, Clean_data_test)
  rmse_foresttemp = mean((Clean_data_test$Streams - yhat_forest_test)^2) %>% sqrt
  rmse_forest = c(rmse_forest, rmse_foresttemp)
}
a=which.min(rmse_forest)
model5=randomForest(Streams ~ ., mtry=a, nTree=100, data=Clean_data_train)

# 2. Boosting:
library(gbm)
boost1 = gbm(Streams ~ ., data=Clean_data_train, 
             interaction.depth=2, n.trees=500, shrinkage=.05)
plot(Streams ~ energy, data=Clean_data_train)
points(predict(boost1, n.trees=500) ~ energy, data=Clean_data_train, pch=19, col='red')
model6 = boost1

#k-fold cross validation
N = nrow(Clean_data)
# Create a vector of fold indicators
K = 10
fold_id = rep_len(1:K, N)  # repeats 1:K over and over again
fold_id = sample(fold_id, replace=FALSE) # permute the order randomly
step_err_save1 = rep(0, K)
step_err_save2 = rep(0, K)
lasso_err_save1 = rep(0, K)
lasso_err_save2 = rep(0, K)
bag_err_save = rep(0,K)
boost_err_save = rep(0,K)
for(i in 1:K) {
  train_set = which(fold_id != i)
  y_test = Clean_data$Streams[-train_set]
  step_model1 = lm(model1, data=Clean_data[train_set,])
  step_model2 = lm(model2, data=Clean_data[train_set,])
  lasso_model1 = lm(model3, data=Clean_data[train_set,])
  lasso_model2 = lm(model4, data=Clean_data[train_set,])
  bag_model = randomForest(Streams ~ ., mtry=a, nTree=100, data=Clean_data[train_set,])
  boost_model = gbm(Streams ~ ., data=Clean_data[train_set,], interaction.depth=2, n.trees=500, shrinkage=.05)
  yhat_test1 = predict(step_model1, newdata=Clean_data[-train_set,])
  step_err_save1[i] = mean((y_test - yhat_test1)^2)
  yhat_test2 = predict(step_model2, newdata=Clean_data[-train_set,])
  step_err_save2[i] = mean((y_test - yhat_test2)^2)
  yhat_test3 = predict(lasso_model1, newdata=Clean_data[-train_set,])
  lasso_err_save1[i] = mean((y_test - yhat_test3)^2)
  yhat_test4 = predict(lasso_model2, newdata=Clean_data[-train_set,])
  lasso_err_save2[i] = mean((y_test - yhat_test4)^2)
  yhat_test5 = predict(bag_model, newdata=Clean_data[-train_set,])
  bag_err_save[i] = mean((y_test - yhat_test5)^2)
  yhat_test6 = predict(boost_model, newdata=Clean_data[-train_set,], n.trees=500)
  boost_err_save[i] = mean((y_test - yhat_test6)^2)
}
# RMSE
c(sqrt(mean(step_err_save1)), sqrt(mean(step_err_save2)), sqrt(mean(lasso_err_save1)), sqrt(mean(lasso_err_save2)), sqrt(mean(bag_err_save)), sqrt(mean(boost_err_save)))
```